### ISSUE TITLE
What's the difference between KIRITAN and KIRITAN_FAST?

### ISSUE THREAD

**Issue by splinter21** [sigprogramming/tyouseisientool#1]

**Comment by sigprogramming** [comment]
This is not an official tool of NEUTRINO.
Information about NEUTRINO is published on the author's Twitter ([@SHACHI_KRTN](https://twitter.com/SHACHI_KRTN)).
There is also a description of the KIRITAN_FAST model there.
KIRITAN_FAST is a model for confirmation use that emphasizes speed.
