### ISSUE TITLE
<再掲>アップデートプログラムについて

### ISSUE THREAD

**Issue by SigumaRoot** [sigprogramming/tyouseisientool#11]
[https://github.com/sigprogramming/tyouseisientool/pull/10#issuecomment-1191736247](先のプルリクエストの応答)にあったようですが、サーバーを見る、というよりは、 [https://qiita.com/takecy/items/690cf140ce2eddacee56](ここ)にもあるようにRSSやAtomを使ってGitHubのリリースを読み取って、tag名のファイルを落としてくるのが理想だと思います。

**Comment by sigprogramming** [comment]
ありがとうございます。返信が遅くなり申し訳ありません。
ご提案いただいたRSSで更新を読んでファイルを落とす方法ですが、
色々調べたところ、NetSparkleを使用して近い形で実装できそうなので、これでやってみます。

**Comment by ghost** [comment]
頑張ってください！
tagとファイル名を一緒にしておけば簡単にできますよ！！
