### ISSUE TITLE
母音脱落記号の入力

### ISSUE THREAD

**Issue by souma987** [sigprogramming/tyouseisientool#14]
現状(v1.8.0.0-beta4)、歌詞に母音脱落記号「'」が入力できないようですが、対応していただけると嬉しいです。

参考：https://studio-neutrino.com/332/ （特殊記号のところ）

**Comment by souma987** [comment]
入力できるときもありました。仕様でしたらすみません。

**Comment by sigprogramming** [comment]
こちら、特殊記号のところに記載されているように、「母音＋子音」「子音＋子音＋母音」など母音を一つ含む形にすると入力できます！子音のみだと入力できないようになっています。

**Comment by souma987** [comment]
今試していて気づいたのですが、一つのノートに母音を含めなければいけないみたいですね。隣接するノートに母音があればいいと私が勘違いしていました。
ご迷惑をお掛けしすみません。素早い対応ありがとうございました。
