### ISSUE TITLE
非圧縮musicxmlファイルをインポートした際、各小節間に空小節が入る

### ISSUE THREAD

**Issue by Sorutrt** [sigprogramming/tyouseisientool#16]
# 問題
musescoreで作成した歌詞なし非圧縮musicxmlファイルを調整支援ツールに入れる際に、元の楽譜の各小節間に空小節が入ります。
具体的には、空小節を`0`、元のデータの小節を `1 2 3 4` とした場合
`1 0 2 0 3 0 4`
というようになります。
# 確認したこと
複数のmusicxmlファイルで確認。
NEUTRINOのRun.batで出力した際には異常なし。
musicxmlファイルをmusescoreで再度開いたときにも異常なし。
# 環境
- Windows10（22H2）
- NEUTRINO v2.1.0
- 調整支援ツール v1.9.0.0
- Musescore 3.6.2

**Comment by sigprogramming** [comment]
issue作成ありがとうございます！

簡単な楽譜をMuseScoreで作成して読み込んでみましたが、空小節が入る現象が確認できなかったので、
読み込み時に空小節が入る楽譜の詳細（テンポ、拍子、タイ、その他含まれている音楽記号など）をお聞きしたいです…！

また、不完全小節になってなっていると正しく読み込めないので、各小節が拍数を満たしているか確認してみてください。

**Comment by Sorutrt** [comment]
返信ありがとうございます！
4/4拍子で、3連符、タイを使用しています。テンポは79で、13小節目で72になっています。
不完全小節はありません。
テンポの変更を消して取り込んでみたのですが、やはり同じ現象が発生します...
問題が発生したファイルを添付します。
ichika-ice_aoi_red.zip

**Comment by sigprogramming** [comment]
詳細ありがとうございます！
ファイルを確認したところ、譜表が複数存在するようなので、使用していない譜表を削除すると正しく読み込めると思います。
MuseScoreで楽器ダイアログ（メニューの[編集] > [楽器]）を開き、使用していない譜表を選択して消去ボタンをクリックで削除できます。

**Comment by Sorutrt** [comment]
ありがとうございます！解決しました。
ヘ音記号の段はト音記号とは別の譜表となることを知らなかったです...
大変お世話になりました！

**Comment by sigprogramming** [comment]
よかったです！！
こちらcloseします！
