### ISSUE TITLE
ノート編集中に予期せぬエラーで落ちる

### ISSUE THREAD

**Issue by lunark** [sigprogramming/tyouseisientool#17]
バグ報告になります。

v1.9.0.0ですが、ノート編集中の何らかの操作（だいたいノート長の編集とか何らかの音符の編集中なのですが、正確にどの動作でおちているかが見えていません）をした際に、予期せぬエラーで落ちています。
本当はどの操作かまで見ようとおもったのですがいまいち条件が掴めず、一旦エラー画面コピペできたのでお送りします。

**環境**
本ツール v1.9.0.0
Neutrino v2.2.0
Windows 11

**エラーダイアログ表記**
```
---------------------------
エラー
---------------------------
予期せぬエラーが発生しました。アプリケーションは終了します。続けて発生する場合は開発者に報告してください。
DispatcherUnhandledException
System.Exception: '種類 'System.Exception' の例外がスローされました。' at TranscribeTiming
System.Collections.ListDictionaryInternal
   場所 NEUTRINOTyouseiSienTool.Entity.Phrase.TranscribeTiming(Phrase phrase)
   場所 NEUTRINOTyouseiSienTool.Entity.NeutrinoContent.<UpdatePhrases>b__74_0(Phrase phrase)
   場所 System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   場所 NEUTRINOTyouseiSienTool.Entity.NeutrinoContent.UpdatePhrases(List`1 phrases)
   場所 NEUTRINOTyouseiSienTool.Infrastructure.TimingPredictionTask.<Process>d__2.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 NEUTRINOTyouseiSienTool.Infrastructure.BackgroundProcessRunner.<ProcessTasks>d__29.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
```

**Comment by sigprogramming** [comment]
ご報告ありがとうございます！反応が遅れてしまい申し訳ありません…！

こちらのエラーですが、以下の情報をお教えいただけると助かります！
- 発生頻度
- 新規作成の場合（一度も保存していない場合）に発生するかどうか
- Undo/Redoやタイミング編集、歌詞の編集など、エラーが発生するまでに行った操作（分かる範囲で大丈夫です）

また、エラーの発生箇所からレンダリング前後の音素データが一致していないっぽいですが、情報が少ないので、ひとまずエラーの詳細を出力するようにしたバージョンをリリースしようと思います。

**Comment by lunark** [comment]
ご連絡ありがとうございます。エラーの発生個所をいただいたところで、ピンときたことがあります。
今回使ったデータはUST→MusicXMLを変換したデータを底本として、調声支援ツール上で再調声していた段階でおきていました。
上記のような変換をしたことでバグの発生したデータ（＝インポートしたMusicXML）には、
・調声支援ツールで作成→書き出しできるMusicXML
・NEUTRINOが推奨しているMuseScoreで作れるMusicXML

と違ってくるところとして、以下の要素を含んでおりました。

・64分音符よりも微妙にクォンタイズがずれたデータを含む
・そもそもクォンタイズされてない音符も含む
・USTの音素がそのまま歌詞に上がってきており
　NEUTRINOに解釈できない音素が歌詞として入っていた（ブレス用の歌詞など）

そういったMusicXMLにおいて

・音の長さ
・歌詞

を修正する段階で起きており、またそのMusicXMLデータをすべてMuseScoreなどほかのツールで楽譜として読める形に訂正後に保存、再読込したところ、ピタリとこの問題が収まりました。

・クォンタイズされていない音符の長さ、発音開始位置の書き換え
・発音できていない歌詞の訂正

を実施しているタイミングで、確かにsigさまの指摘されている「レンダリング前後での音素データの不一致」はおきそうだとおもいます。以上、追加報告になります。

**Comment by lunark** [comment]
続報です。

新規作成でも、レンダリングが完了する前に、同じphraseに対してレンダリング中に何度か修正をかけていると発現するかもしれません。再現できそうでしょうか？
検証環境をそろえる目的でも、正確なバージョンを取りました。
NEUTRINO-2.2.1、Model側はMELLOWの2.2.1、KIRITANの2.2.1ともに発生しています。ほかのmodelは未テストです。
よろしくお願いいたします。

**Comment by sigprogramming** [comment]
データの詳細等ありがとうございます！なるほどです！

> 新規作成でも、レンダリングが完了する前に、同じphraseに対してレンダリング中に何度か修正をかけていると発現するかも

こちらの「新規作成」は「MusicXMLをインポートして未保存の状態」でしょうか？

**Comment by lunark** [comment]
こちらですが、MusicXMLをインポートして未保存の状態でも、MusicXMLを伴わずに新規作成ボタンを押して普通に打ち込んでいるときにも発現します。

なので、おそらくプレビュー用の音声を作っている（裏でレンダリングが走っている）ときに何度も何度も同じ場所の音の長さやタイミングを変えるときに偶発的に起きる…みたいな感じなのかなぁとは思っています。
エラーの詳細が出るバージョンをリリースいただければテストいたしますよー！

**Comment by sigprogramming** [comment]
ありがとうございます！普通に打ち込んでいて発生するんですね…
レンダリング周りの処理の不具合かもしれないです。
エラーの詳細（エラーが発生したフレーズの歌詞と音素）を出力するようにしたバージョンをリリースしましたので、こちらお試しいただけると助かります…！
https://github.com/sigprogramming/tyouseisientool/releases/tag/v1.9.0.1

**Comment by lunark** [comment]
https://gist.github.com/lunark/acc25dc5db2792fe0792991940b2e478
ありがとうございます！　エラーログファイルの内容をGistにupしましたのでお送りします。
エラー個所はこんな感じです。
直前の操作でレンダリング中にブレスをON/OFFしたかがちょっと記憶にないのですが、
brとpauの扱いが変わるところなどで何かが起きてるかもしれません。

System.Exception: 'Phonemes of phrases do not match. 
src_lyrics   : もっ と もっ と も と と ち か づ い て 
src_phonemes : m o cl t o m o cl t o m o t o t o ch i k a z u i t e br 
dest_lyrics  : もっ と もっ と も と と ち か づ い て 
dest_phonemes: m o cl t o m o cl t o m o t o t o ch i k a z u i t e pau' at TranscribeTiming

いったん中間報告です！

**Comment by sigprogramming** [comment]
エラーの詳細ありがとうございます！助かります…！
こちらでもエラーを再現できました。
ブレスの後ろの音符をずらしてブレスの直後に休符をつくるとエラーになるようです。
フレーズを更新する処理に不具合がありそうなので、この辺りを調査してみます。

**Comment by lunark** [comment]
私のほうでも再現できました。
ちなみにですが、ブレスの直後に休符がある状態から、休符をなくす（pau→brに置き換わる）ケースでもエラーになるようです。
またv1.8系列でも同じExceptionで落ちるので、1.8にも共通したバグかもしれません。

**Comment by sigprogramming** [comment]
こちら、[v1.8.0.2](https://github.com/sigprogramming/tyouseisientool/releases/tag/v1.8.0.2)、[v1.9.0.2](https://github.com/sigprogramming/tyouseisientool/releases/tag/v1.9.0.2)で修正しました！
フレーズを更新する処理でブレスの直後の休符の有無をチェックできていなかったので、チェックするように修正しました。
ご報告とても助かりました！

**Comment by lunark** [comment]
おぉぉ！よかったです。確認してみましたが今回のバグについては収まっていると思います。
ご対応ありがとうございました！
（なお、今回バグの出方が直す前に判明してたので、何とか回避しながら1曲作れました！合わせて感謝です。
　お礼といってはなんですが、私の調声動画のマイリス番号でも投棄してまいります…mylist/2536870）

**Comment by sigprogramming** [comment]
ご確認ありがとうございます、良かったです！
（マイリスもありがとうございます、拝聴させていただきます！）
こちら解決ということで、closeしたいと思います。
