### ISSUE TITLE
The GUI seems wrong.

### ISSUE THREAD

**Issue by splinter21** [sigprogramming/tyouseisientool#2]
win10
Simplified Chinese
version of the tool is v1.4.0.0(x64)
![搜狗截图20200524170936](https://user-images.githubusercontent.com/26759495/82750261-7b4bf780-9de1-11ea-9fde-1fe5a2ae5b64.png)

**Comment by sigprogramming** [comment]
This screen is the state before the file is loaded.
It would be very helpful if you could write down specifically what is wrong.
If there are no problems, close the issue.
