### ISSUE TITLE
[other] main page says the latest release is 1.8.0.3

### ISSUE THREAD

**Issue by blackhomotoadshoe** [sigprogramming/tyouseisientool#27]
is it supposed to like that despite actual latest release being 1.9.0.3? i've seen people complain that they can't bring gui to work with 2.x/muon libraries only for then to turn out they downloaded 1.8.0.3 because main says it's the latest release and not 1.9.0.3

**Comment by sigprogramming** [comment]
Thank you for your report!
I have set v1.9.0.3 as the latest release.
