### ISSUE TITLE
Runing Neutrino error (WORLD.dll)

### ISSUE THREAD

**Issue by Liniuwuu** [sigprogramming/tyouseisientool#6]
![error](https://user-images.githubusercontent.com/59339248/109007785-4bd95c80-768b-11eb-86b5-24d209dfba2d.png)
When the run process is completed, i close, and appears the error:
"An unexpected error has occured. The application will be closed. Please report to the developer if it continues to occur. (The DLL 'WORLD.dll' could not be loaded. It is not possible to find the specified module. Exception at HRESULT: 0x8007007E) To MallocF0)"
(v1.5.1.0)

(Error message translated into English)

**Comment by moonstarsky37** [comment]
Can you check the WORLD.dll file inside the folder "NEUTRINOTyouseiSienTool-v1.5.1.0-x64\bin"?

**Comment by sigprogramming** [comment]
Please check if .NET Framework 4.7.2 is installed.
