### ISSUE TITLE
東北イタコ以降の新音源への対応

### ISSUE THREAD

**Issue by cyatarow** [sigprogramming/tyouseisientool#7]
開発が止まっているようですが

**Comment by moonstarsky37** [comment]
Maybe my way I used can give it a try. I analysis the execute file and the model default is setting as KIRITAN under the NEUTRINO\model folder, and just replace the file inside this it can used another vocal model.
I test using the vocal: SEVEN is fine.  The results share as following
https://sndup.net/88x5

**Comment by sigprogramming** [comment]
更新が止まってしまいすみませんでした。現時点でリリースされているライブラリに対応しました。
