### ISSUE TITLE
Can't open musicxml with using NEUTRINO v0.430

### ISSUE THREAD

**Issue by kidapu** [sigprogramming/tyouseisientool#8]
I can open musicxml with using NEUTRINO v0.420, but can't open same musicxml with using v0.430.

![スクリーンショット 2021-04-11 221046](https://user-images.githubusercontent.com/720154/114305402-070e6580-9b13-11eb-89ad-749bb835354b.png)

My environment is below.
- Windows OS 10 Home version 10.0.19042

**Comment by moonstarsky37** [comment]
I test the latest version (v0.431) is now can open 3 samples under the score\musicxml.  Maybe you can test new version.
![圖片](https://user-images.githubusercontent.com/9031339/131251159-769be143-578a-4a6b-8091-7242699d7e21.png)

**Comment by kidapu** [comment]
I'm also able to confirm this works with the latest version.
Thank you for telling!
