### ISSUE TITLE
インストーラー作成に伴いソースコードの開示要求と、新機能の提案

### ISSUE THREAD

**Issue by SigumaRoot** [sigprogramming/tyouseisientool#9]
今、このソフトウェアをもっと簡単に使用可能にするために、インストーラーを作成しているものです。

インストーラーを作成している際に、NEUTORINO本体ごとインストールできればいいと思いました。そして、ライブラリを、オンラインからGUIでインストールできれば、もっと簡単になると考えたのですが、ソースコードがないため、開発することができません。

なお、wikiがあると使いやすいと思うので、それもお願いします。

必要があれば手伝わせていただきますので、お気軽にご連絡ください。

質問事項と、要求事項：
- 使用言語
- ソースコードの公開
- wikiの開設

**Comment by sigprogramming** [comment]
ご提案とインストーラーの作成ありがとうございます。

NEUTRINO本体とライブラリのインストールですが、配布ファイルの名前と場所の変更に対応するために、
それらの情報をこちらで用意したサーバーに置いて、それを元にツール側でDL等を行う必要があると思います。
（何か他に良い方法がありましたら教えていただけると幸いです。）

また、NEUTRINOフォルダの設定が面倒なことと、ライブラリをインストールするUIが無いことは
改善点だと思っていますので、これらの改善を検討してみます。 

ソースコードの公開についてですが、
このソフトは私が初めて作成したもので、設計が十分にできていないので、
レンダリング周りの実装が終わった後にmac対応も兼ねて作り直すことを考えています。
その際、可能であればオープンソースにしようと考えていますので、
よろしければそちらで開発に参加していただけると大変助かります。
使用言語はC#です。

wikiについては、私も必要だと感じていたので、編集でき次第公開しようと思います。

**Comment by SigumaRoot** [comment]
わかりました。

できることがあれば手伝いますので、その時はぜひお声掛けください。

**Comment by ghost** [comment]
ソースコードに時間がかかるということでしたので、勝手にデコンパイルしてもいいですか？

**Comment by sigprogramming** [comment]
デコンパイル自体は可能ですが、ソースコードの利用（複製、改変、再頒布）はしないようお願いいたします。
